import pandas as pd
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

def load_data(filepath="data/exports/vehicle_speed_summary.csv"):
    """Loads the vehicle speed summary data."""
    if not os.path.exists(filepath):
        # Fallback for relative paths if run from different directories
        filepath = os.path.join("..", filepath)
    
    if os.path.exists(filepath):
        return pd.read_csv(filepath)
    else:
        return None

def generate_prompt(question, df):
    """
    Generates a prompt for an LLM that includes the dataframe structure and the user's question.
    """
    if df is None:
        return f"Error: Could not load data to answer question: {question}"

    # Get data structure info
    columns = df.columns.tolist()
    sample_data = df.head(3).to_markdown(index=False)
    
    # Calculate some basic stats to give the LLM context
    total_records = len(df)
    triggers = len(df[df['status'] == 'TRIGGER'])
    warnings = len(df[df['status'] == 'WARNING'])
    
    prompt = f"""
    You are an AI assistant for the NYC Safe Streets ISA (Intelligent Speed Assistance) pilot program.
    You have access to a dataset of vehicle speeding violations.
    
    ### Dataset Structure:
    - Total Records: {total_records}
    - Columns: {', '.join(columns)}
    - 'status' column values: TRIGGER (Mandatory Install), WARNING (At Risk), OK
    - TRIGGER count: {triggers}
    - WARNING count: {warnings}
    
    ### Domain Rules & System Context:
    1. **The Goal**: Monitor 'super-speeders' for mandatory Intelligent Speed Assistance (ISA) installation.
    2. **Trigger Rule**: A vehicle is flagged as 'TRIGGER' if it accumulates **16 or more speed camera tickets** within a **12-month trailing window**.
    3. **Warning Rule**: Vehicles with 12-15 tickets are 'WARNING'.
    4. **Data Source**: This data comes from the `vehicle_speed_summary` table, which is generated by the **ISA Engine**. 
    5. **Pipeline**: The engine aggregates data from the immutable `speed_historic` ground truth and normalized county updates (`norm_*` views).
    
    ### Sample Data (First 3 rows):
    {sample_data}
    
    ### User Question:
    {question}
    
    ### Instructions:
    Answer the user's question based on the dataset summary and structure provided above.
    If the question requires precise calculation that you cannot perform on the summary, explain the logic of how to query the dataset.
    """
    return prompt

if __name__ == "__main__":
    # Example Usage
    df = load_data()
    
    if df is not None:
        print("Data Loaded Successfully.")
        
        # Example Question
        question = "How many vehicles are currently flagged for mandatory ISA installation?"
        
        prompt = generate_prompt(question, df)
        
        print("\n--- Generated Prompt ---")
        print(prompt)
        print("\n------------------------")
        
        # Placeholder for LLM call
        azure_api_key = os.getenv("AZURE_OPENAI_4O_API_KEY")
        azure_endpoint = os.getenv("AZURE_OPENAI_4O_ENDPOINT")
        
        if azure_api_key and azure_endpoint:
            print(f"Azure API Key found: {azure_api_key[:5]}...")
            print(f"Azure Endpoint: {azure_endpoint}")
            print("Ready to initialize AzureOpenAI client with deployment:", os.getenv("AZURE_OPENAI_4O_DEPLOYMENT"))
        else:
            print("No Azure API credentials set in .env file.")
    else:
        print("Could not find data file.")
